cmake_minimum_required(VERSION 3.22)
project(mattmux_mediainfo LANGUAGES C CXX)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(BUILD_SHARED_LIBS OFF)
set(BUILD_ZENLIB ON CACHE BOOL "" FORCE)
set(BUILD_ZLIB OFF CACHE BOOL "" FORCE)
set(CMAKE_DISABLE_FIND_PACKAGE_CURL ON)
set(CMAKE_DISABLE_FIND_PACKAGE_TinyXML ON)
add_subdirectory("${MEDIAINFO_SOURCE}/Project/CMake" mediainfo)
add_library(mediainfo_jni SHARED mediainfo_jni.cpp)
target_include_directories(mediainfo_jni PRIVATE "${MEDIAINFO_SOURCE}/Source" "${MEDIAINFO_SOURCE}/../ZenLib/Source")
target_link_libraries(mediainfo_jni PRIVATE mediainfo)
target_link_options(mediainfo_jni PRIVATE -Wl,-z,max-page-size=16384)
